Name: Rahul Yadav
Class: SYIT
Roll No.: 51
Subject: Python for Data Structure
Date: 30/09/2026

1. Import a CSV dataset using Pandas.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movies.csv")

2. Find missing values in the dataset.

In [3]:
df.isnull().sum()

imdbId           0
title            0
releaseYear      0
releaseDate     53
genre            2
writers        119
actors           3
directors        4
sequel           3
hitFlop          0
dtype: int64

3. Replace missing numerical values with the mean.

In [4]:
num_cols = df.select_dtypes(include="number").columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

df

,imdbId,title,releaseYear,releaseDate,genre,writers,actors,directors,sequel,hitFlop
0,tt0118578,Albela,2001,20 Apr 2001,Romance,Honey Irani (screenplay) | Honey Irani (story)...,Govinda | Aishwarya Rai Bachchan | Jackie Shro...,Deepak Sareen,0.0,2
1,tt0169102,Lagaan: Once Upon a Time in India,2001,08 May 2002,Adventure | Drama | Musical,Ashutosh Gowariker (story) | Ashutosh Gowarike...,Aamir Khan | Gracy Singh | Rachel Shelley | Pa...,Ashutosh Gowariker,0.0,6
2,tt0187279,Meri Biwi Ka Jawab Nahin,2004,02 Jul 2004,Action | Comedy,NaN,Akshay Kumar | Sridevi | Gulshan Grover | Laxm...,Pankaj Parashar | S.M. Iqbal,0.0,1
3,tt0222024,Hum Tumhare Hain Sanam,2002,24 May 2002,Drama | Romance,K.S. Adiyaman | Arun Kumar (assistant dialogue...,Shah Rukh Khan | Madhuri Dixit | Salman Khan |...,K.S. Adiyaman,0.0,4
4,tt0227194,One 2 Ka 4,2001,30 Mar 2001,Action | Comedy | Drama,Sanjay Chhel | Raaj Kumar Dahima (screenplay) ...,Shah Rukh Khan | Juhi Chawla | Jackie Shroff |...,Shashilal K. Nair,0.0,1
...,...,...,...,...,...,...,...,...,...,...
1279,tt4121522,Shuruaat Ka Interval,2014,15 Aug 2014,NaN,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,Kaivalya Chheda | Rajsekhar Aningi | Avidant B...,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,0.0,1
1280,tt4187650,Trip to Bhangarh,2014,28 Aug 2014,Horror,NaN,Manish Choudhary | Suzanna Mukherjee | Poonam ...,Jitendra Pawar,0.0,1
1281,tt4190220,Zed Plus,2014,28 Nov 2014,NaN,Chandra Prakash Dwivedi (screen play and dialo...,Adil Hussain | Ekavali Khanna | Kulbhushan Kha...,Chandra Prakash Dwivedi,0.0,1
1282,tt4219300,Gollu aur Pappu,2014,21 Nov 2014,Comedy,NaN,Vir Das | Sandeepa Dhar | Rahul Handa | Dimple...,Kabir Sadanand,0.0,1
1283,tt4228746,Zid,2014,28 Nov 2014,Thriller,Vivek Agnihotri | Rohit Malhotra,Shradha Das | Mohan Kapoor | Mannara | Karanvi...,Rohit Malhotra | Anubhav Sinha,0.0,2

4. Remove duplicate records.

In [5]:
df = df.drop_duplicates()

5. Display the cleaned dataset.

In [6]:
df

,imdbId,title,releaseYear,releaseDate,genre,writers,actors,directors,sequel,hitFlop
0,tt0118578,Albela,2001,20 Apr 2001,Romance,Honey Irani (screenplay) | Honey Irani (story)...,Govinda | Aishwarya Rai Bachchan | Jackie Shro...,Deepak Sareen,0.0,2
1,tt0169102,Lagaan: Once Upon a Time in India,2001,08 May 2002,Adventure | Drama | Musical,Ashutosh Gowariker (story) | Ashutosh Gowarike...,Aamir Khan | Gracy Singh | Rachel Shelley | Pa...,Ashutosh Gowariker,0.0,6
2,tt0187279,Meri Biwi Ka Jawab Nahin,2004,02 Jul 2004,Action | Comedy,NaN,Akshay Kumar | Sridevi | Gulshan Grover | Laxm...,Pankaj Parashar | S.M. Iqbal,0.0,1
3,tt0222024,Hum Tumhare Hain Sanam,2002,24 May 2002,Drama | Romance,K.S. Adiyaman | Arun Kumar (assistant dialogue...,Shah Rukh Khan | Madhuri Dixit | Salman Khan |...,K.S. Adiyaman,0.0,4
4,tt0227194,One 2 Ka 4,2001,30 Mar 2001,Action | Comedy | Drama,Sanjay Chhel | Raaj Kumar Dahima (screenplay) ...,Shah Rukh Khan | Juhi Chawla | Jackie Shroff |...,Shashilal K. Nair,0.0,1
...,...,...,...,...,...,...,...,...,...,...
1279,tt4121522,Shuruaat Ka Interval,2014,15 Aug 2014,NaN,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,Kaivalya Chheda | Rajsekhar Aningi | Avidant B...,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,0.0,1
1280,tt4187650,Trip to Bhangarh,2014,28 Aug 2014,Horror,NaN,Manish Choudhary | Suzanna Mukherjee | Poonam ...,Jitendra Pawar,0.0,1
1281,tt4190220,Zed Plus,2014,28 Nov 2014,NaN,Chandra Prakash Dwivedi (screen play and dialo...,Adil Hussain | Ekavali Khanna | Kulbhushan Kha...,Chandra Prakash Dwivedi,0.0,1
1282,tt4219300,Gollu aur Pappu,2014,21 Nov 2014,Comedy,NaN,Vir Das | Sandeepa Dhar | Rahul Handa | Dimple...,Kabir Sadanand,0.0,1
1283,tt4228746,Zid,2014,28 Nov 2014,Thriller,Vivek Agnihotri | Rohit Malhotra,Shradha Das | Mohan Kapoor | Mannara | Karanvi...,Rohit Malhotra | Anubhav Sinha,0.0,2